### ISSUE TITLE
Error while running the "python -W ignore test.py"

### ISSUE THREAD

**Issue by MascareneHigh** [swpowell/raintype_python#3]
I was following the steps provided but i encountered an error when i was running this command. Upon checking, it was found that the issue is with the "np.int" written in the algorithim.py file. "convsfmat = 10 * np.ones(refl.shape, dtype=np.int)" - this line was showing the error. we cahnged it to np.int64 still it was showing error. 

here is the error:  
File "C:\Users\SHREYASI UPADHYAY\Downloads\raintype_python-master\raintype_python-master\uw_raintype\runraintype.py", line 195, in <module>
    (rtout,types) = rt.raintype(fname, fileDir, refl, refl_missing_val=missing_value,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHREYASI UPADHYAY\AppData\Roaming\Python\Python311\site-packages\uw_raintype-1.0-py3.11.egg\uw_raintype\raintype.py", line 134, in raintype
    rtout = alg.convectivecore(background,refl,minZdiff,types,dBZformaxconvradius,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHREYASI UPADHYAY\AppData\Roaming\Python\Python311\site-packages\uw_raintype-1.0-py3.11.egg\uw_raintype\algorithm.py", line 14, in convectivecore
    convsfmat = 10 * np.ones(refl.shape, dtype=np.int64)
                                              ^^^^^^
  File "D:\New folder\envs\rain\Lib\site-packages\numpy\__init__.py", line 338, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?

**Comment by swpowell** [comment]
Pushed update replacing np.int with int and error is not occurring.
